# -*- coding: utf-8 -*-
"""EML QUIZ.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14Ajpqbn2IvXZ3mIksgl6yrjYRxEzfXFh
"""

!wget http://www.vision.caltech.edu/Image_Datasets/Caltech101/101_ObjectCategories.tar.gz

!tar -xvzf '101_ObjectCategories.tar.gz'

from keras import applications
from keras.preprocessing.image import ImageDataGenerator
from keras.layers import Flatten, Dropout, Dense, Activation
from keras.models import Sequential, Model

model = applications.InceptionV3(include_top=False, input_shape=(256,256,3))

img_width, img_height = 256, 256
nb_validation_samples = 466 
batch_size = 16
epochs = 50

x = model.output
x = Flatten()(x)
x = Dense(1024, activation="relu")(x)
x = Dropout(0.5)(x)
x = Dense(1024, activation="relu")(x)
predictions = Dense(102, activation="softmax")(x)

model_final = Model(input = model.input, output = predictions)

model_final.compile(loss = "categorical_crossentropy", 
                    optimizer = 'SGD',
                    metrics=["accuracy"])

# Initiate the train and test generators with data Augumentation 
train_datagen = ImageDataGenerator(
rescale = 1./255,
horizontal_flip = True,
fill_mode = "nearest",
zoom_range = 0.3,
width_shift_range = 0.3,
height_shift_range=0.3,
rotation_range=30)

test_datagen = ImageDataGenerator(
rescale = 1./255,
horizontal_flip = True,
fill_mode = "nearest",
zoom_range = 0.3,
width_shift_range = 0.3,
height_shift_range=0.3,
rotation_range=30)

train_generator = train_datagen.flow_from_directory(
'101_ObjectCategories',
target_size = (img_height, img_width),
batch_size = batch_size, 
class_mode = "categorical")

# Train the model 
model_final.fit_generator(
train_generator,
samples_per_epoch = 200,
epochs = 10,)
