import turtle

class name_initials(object):

    def for_d(self):
        d = turtle.Turtle()
        d.color("white")
        d.left(180)
        d.forward(230)
        d.right(180)
        d.color("red")
        d.circle(40, 180)
        d.left(90)
        d.forward(80)
        d.left(90)
        d.forward(5)

    def for_a(self):
        a = turtle.Turtle()
        a.color("white")
        a.left(180)
        a.forward(180)
        a.right(180)
        a.color("white")
        a.forward(20)
        a.color("red")
        a.circle(15, 450)
        a.right(150)
        a.forward(20)
        a.left(60)

    def for_n(self):
        n = turtle.Turtle()
        n.color("white")
        n.left(180)
        n.forward(90)
        n.right(180)
        n.color("red")
        n.left(90)
        n.forward(20)
        n.circle(20,180)
        n.forward(20)
        n.right(180)
        n.forward(45)

    def for_i(self):
        i = turtle.Turtle()
        i.color("white")
        i.left(180)
        i.forward(70)
        i.color("red")
        i.right(90)
        i.forward(20)
        i.color("white")
        i.forward(15)
        i.color("red")
        i.forward(5)
        i.right(90)

    def for_s(self):
        s = turtle.Turtle()
        s.color("white")
        s.left(180)
        s.forward(60)
        s.right(270)
        s.color("red")
        s.left(90)
        s.forward(20)
        s.left(90)
        s.forward(20)
        s.left(90)
        s.forward(20)
        s.right(90)
        s.forward(20)
        s.right(90)
        s.forward(20)

    def for_h(self):
        h = turtle.Turtle()
        h.color("white")
        h.left(180)
        h.forward(30)
        h.right(90)
        h.forward(40)
        h.right(180)
        h.color("red")
        h.forward(40)
        h.left(180)
        h.forward(20)
        h.right(90)
        h.forward(20)
        h.right(90)
        h.forward(20)
        h.left(90)

    def __init__(self):
        self.on = False
        space = turtle.Turtle()
        space.color("white")
        self.for_d()
        space.forward(50)
        self.for_a()
        space.forward(50)
        self.for_n()
        space.forward(10)
        self.for_i()
        space.forward(10)
        self.for_s()
        space.forward(50)
        self.for_h()
        space.right(90)
        turtle.exitonclick()


danish = name_initials()
